name: Testing environments

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  VERSION: ${GITHUB_REF_NAME#v}

jobs:
  prod:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.APP_URL }}
    steps:
      - name: Display the tag
        run: echo "${{ github.ref_name }} ;; ${{ env.VERSION }} "

      - name: Display variables
        run: echo "${{ env.PROJECT_ID }} ;; ${{ vars.APP_URL }}"

      - name: Display secrets
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: echo "${{ env.GCP_PROJECT }} ;; ${{ env.GCP_CREDENTIALS }}"

  staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ vars.APP_URL }}
    steps:
      - name: Display the tag
        run: echo "${{ github.ref_name }} ;; ${{ env.VERSION }} "

      - name: Display variables
        run: echo "${{ env.PROJECT_ID }} ;; ${{ vars.APP_URL }}"

      - name: Display secrets
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: echo "${{ env.GCP_PROJECT }} ;; ${{ env.GCP_CREDENTIALS }}"
