name: Testing environments

on:
  push:
    tags:
      - '^v[0-9]+\.[0-9]+\.[0-9]+'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REPOSITORY: my-app
  REGION: europe-west9

jobs:
  prod:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.APP_URL }}
    steps:
      - name: Display the tag
        run: echo ${{ github.ref }}
      
      - name: Display variables
        run: echo "${{ env.PROJECT_ID }} ;; ${{ vars.APP_URL }}"

      - name: Display secrets
        run: echo "${{ secrets.GCP_PROJECT }} ;; ${{ secrets.GCP_CREDENTIALS }}"
  
  staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ vars.APP_URL }}
    steps:
      - name: Display the tag
        run: echo ${{ github.ref }}
      
      - name: Display variables
        run: echo "${{ env.PROJECT_ID }} ;; ${{ vars.APP_URL }}"

      - name: Display secrets
        run: echo "${{ secrets.GCP_PROJECT }} ;; ${{ secrets.GCP_CREDENTIALS }}"
 